export const OPEN_THE_MODAL_TASK_WINDOW = 'OPEN_THE_MODAL_TASK_WINDOW';
export const OPEN_THE_MODAL_SPELL_WINDOW = 'OPEN_THE_MODAL_SPELL_WINDOW';
export const OPEN_THE_TASK_WINDOW = 'OPEN_THE_TASK_WINDOW';